export type CommodityTier =
  | 'Primary'
  | 'SecondaryProcessedFood'
  | 'SecondaryRefiningMaterial'
  | 'TertiaryHighTech'
  | 'SpecialReward';

export type CommodityConfig = {
  readonly name: string;
  readonly tier: CommodityTier;
  readonly minResidentialTier: number | null;
  readonly role: string;
  readonly source: string;
};

export type ProductionRecipe = {
  readonly output: string;
  readonly inputs: Readonly<Record<string, number>>;
  readonly energyCost: number;
  readonly satietyCost: number;
  readonly timeCostSeconds: number;
  readonly rewardProbabilityPercent: number;
  readonly source: string;
};

const commoditySource = 'AIvilization v0 Appendix B Table 7';
const recipeSource = 'AIvilization v0 Appendix B Table 9';

export const commodities = [
  {
    name: 'Apple',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Food processing input / Basic consumption good',
    source: commoditySource,
  },
  {
    name: 'Wheat',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Food processing input / Basic consumption good',
    source: commoditySource,
  },
  {
    name: 'Rice',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Food processing input / Basic consumption good',
    source: commoditySource,
  },
  {
    name: 'Wood',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Industrial raw material',
    source: commoditySource,
  },
  {
    name: 'Book',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Basic consumption good',
    source: commoditySource,
  },
  {
    name: 'Copper Ore',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Industrial raw material',
    source: commoditySource,
  },
  {
    name: 'Iron Ore',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Industrial raw material',
    source: commoditySource,
  },
  {
    name: 'Silicon Ore',
    tier: 'Primary',
    minResidentialTier: 1,
    role: 'Industrial raw material',
    source: commoditySource,
  },
  {
    name: 'Beef',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 2,
    role: 'Food processing input / Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Chicken',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 2,
    role: 'Food processing input / Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Fish',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Food processing input / Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Flour',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Food processing input / Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Bread',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Sushi',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Apple Pie',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Chicken Salad',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Beef Rice',
    tier: 'SecondaryProcessedFood',
    minResidentialTier: 3,
    role: 'Secondary consumption good',
    source: commoditySource,
  },
  {
    name: 'Coal',
    tier: 'SecondaryRefiningMaterial',
    minResidentialTier: 4,
    role: 'Industrial intermediate',
    source: commoditySource,
  },
  {
    name: 'Copper Ingot',
    tier: 'SecondaryRefiningMaterial',
    minResidentialTier: 4,
    role: 'Industrial intermediate',
    source: commoditySource,
  },
  {
    name: 'Iron Ingot',
    tier: 'SecondaryRefiningMaterial',
    minResidentialTier: 4,
    role: 'Industrial intermediate',
    source: commoditySource,
  },
  {
    name: 'Pure Silicon',
    tier: 'SecondaryRefiningMaterial',
    minResidentialTier: 4,
    role: 'Industrial intermediate',
    source: commoditySource,
  },
  {
    name: 'Transistor',
    tier: 'TertiaryHighTech',
    minResidentialTier: 5,
    role: 'High-tech intermediate',
    source: commoditySource,
  },
  {
    name: 'Circuit Board',
    tier: 'TertiaryHighTech',
    minResidentialTier: 5,
    role: 'High-tech intermediate',
    source: commoditySource,
  },
  {
    name: 'Chip',
    tier: 'TertiaryHighTech',
    minResidentialTier: 5,
    role: 'High-tech consumption goods',
    source: commoditySource,
  },
  {
    name: 'Gold Apple',
    tier: 'SpecialReward',
    minResidentialTier: null,
    role: 'Rare reward item, not a regular production target',
    source: commoditySource,
  },
] as const satisfies readonly CommodityConfig[];

export const productionRecipes = [
  {
    output: 'Apple',
    inputs: {},
    energyCost: 2,
    satietyCost: 0,
    timeCostSeconds: 0.1,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Wheat',
    inputs: {},
    energyCost: 12,
    satietyCost: 3,
    timeCostSeconds: 0.6,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Rice',
    inputs: {},
    energyCost: 16,
    satietyCost: 4,
    timeCostSeconds: 0.8,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Wood',
    inputs: {},
    energyCost: 8,
    satietyCost: 2,
    timeCostSeconds: 0.4,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Book',
    inputs: { Wood: 1 },
    energyCost: 32,
    satietyCost: 8,
    timeCostSeconds: 1.6,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Copper Ore',
    inputs: {},
    energyCost: 12,
    satietyCost: 3,
    timeCostSeconds: 0.6,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Iron Ore',
    inputs: {},
    energyCost: 16,
    satietyCost: 4,
    timeCostSeconds: 0.8,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Silicon Ore',
    inputs: {},
    energyCost: 20,
    satietyCost: 5,
    timeCostSeconds: 1,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Beef',
    inputs: { Wheat: 2 },
    energyCost: 24,
    satietyCost: 6,
    timeCostSeconds: 1.2,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Chicken',
    inputs: { Wheat: 1 },
    energyCost: 20,
    satietyCost: 5,
    timeCostSeconds: 1,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Fish',
    inputs: {},
    energyCost: 60,
    satietyCost: 15,
    timeCostSeconds: 3,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Flour',
    inputs: { Wheat: 1 },
    energyCost: 20,
    satietyCost: 5,
    timeCostSeconds: 1,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Bread',
    inputs: { Flour: 1 },
    energyCost: 36,
    satietyCost: 9,
    timeCostSeconds: 1.8,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Sushi',
    inputs: { Rice: 1, Fish: 1 },
    energyCost: 40,
    satietyCost: 10,
    timeCostSeconds: 2,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Apple Pie',
    inputs: { Apple: 1, Flour: 1 },
    energyCost: 40,
    satietyCost: 10,
    timeCostSeconds: 2,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Chicken Salad',
    inputs: { Chicken: 1, Flour: 1 },
    energyCost: 20,
    satietyCost: 5,
    timeCostSeconds: 1,
    rewardProbabilityPercent: 0.5,
    source: recipeSource,
  },
  {
    output: 'Beef Rice',
    inputs: { Rice: 1, Beef: 1 },
    energyCost: 40,
    satietyCost: 10,
    timeCostSeconds: 2,
    rewardProbabilityPercent: 0.8,
    source: recipeSource,
  },
  {
    output: 'Coal',
    inputs: { Wood: 1 },
    energyCost: 40,
    satietyCost: 10,
    timeCostSeconds: 2,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Copper Ingot',
    inputs: { Wood: 1, 'Copper Ore': 1 },
    energyCost: 48,
    satietyCost: 12,
    timeCostSeconds: 2.4,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Iron Ingot',
    inputs: { 'Iron Ore': 1, Coal: 1 },
    energyCost: 52,
    satietyCost: 13,
    timeCostSeconds: 2.6,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Pure Silicon',
    inputs: { 'Silicon Ore': 1, Coal: 1 },
    energyCost: 56,
    satietyCost: 14,
    timeCostSeconds: 2.8,
    rewardProbabilityPercent: 0,
    source: recipeSource,
  },
  {
    output: 'Transistor',
    inputs: { 'Copper Ingot': 1, 'Iron Ingot': 1 },
    energyCost: 60,
    satietyCost: 15,
    timeCostSeconds: 3,
    rewardProbabilityPercent: 1,
    source: recipeSource,
  },
  {
    output: 'Circuit Board',
    inputs: { 'Copper Ingot': 1, 'Pure Silicon': 1 },
    energyCost: 80,
    satietyCost: 20,
    timeCostSeconds: 4,
    rewardProbabilityPercent: 2,
    source: recipeSource,
  },
  {
    output: 'Chip',
    inputs: { Transistor: 1, 'Circuit Board': 1 },
    energyCost: 100,
    satietyCost: 25,
    timeCostSeconds: 5,
    rewardProbabilityPercent: 5,
    source: recipeSource,
  },
] as const satisfies readonly ProductionRecipe[];
