export const OBSERVER_HTML = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Town · 居民实验室</title>
<style>body{margin:0;background:#101b20;color:#e6ece5;font:16px system-ui}main{max-width:1100px;margin:auto;padding:40px}h1{font-size:38px;letter-spacing:-1px}.tag{color:#91bdaa}input,button{padding:12px;border:1px solid #517466;border-radius:8px;background:#1b2b30;color:inherit}input{width:min(70%,520px)}button{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}article{background:#1b2b30;border:1px solid #345047;border-radius:14px;padding:20px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.6 monospace}summary{cursor:pointer}#status{padding:18px 0}h2{margin-top:35px}small{color:#afc2b7}</style>
<main><div class="tag">AIvilization · OPEN AGENT SOCIETY</div><h1>居民实验室</h1><p>从意图、工具到真实结果。管理员观察视角；居民只接收自己的有限信息。</p>
<form id="login"><label for="token">管理员凭证</label><p><input id="token" type="password" autocomplete="off" required> <button>读取 / 刷新</button></p></form><small>凭证位于实验目录 credentials.json 的 admin 字段，仅保存在当前页面内存。</small><div id="status" role="status"></div><h2>城市公共应用</h2><p>按入口查找作者原文；不生成摘要、评分或共识。</p><section id="apps" class="grid"></section><section id="app-content" aria-live="polite"></section><h2>居民状态</h2><section id="people" class="grid"></section><section id="details"></section></main>
<script src="/observer.js"></script></html>`;
export const OBSERVER_JS = `const form=document.getElementById('login');const status=document.getElementById('status');
function node(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function original(doc){const d=node('details','');d.append(node('summary',doc.title||doc.path),node('small','作者 '+doc.authorId+' · 版本 '+doc.revision+' · 时间 '+doc.updatedAt),node('pre',doc.content));return d}
function showChannel(data,channel){const panel=document.getElementById('app-content');panel.replaceChildren(node('h2',channel.title));
const docs=data.documents.filter(d=>d.spaceId===channel.spaceId&&!d.deleted);
const guide=docs.find(d=>d.path===channel.guidePath);if(guide)panel.append(original(guide));
const posts=docs.filter(d=>d.path.startsWith('posts/')).sort((a,b)=>a.createdAt-b.createdAt||(a.id<b.id?-1:a.id>b.id?1:0));
panel.append(node('p','居民投稿 · '+posts.length+' 篇 · 按发布时间与 ID 排序'));
for(const doc of posts){const section=node('article','');section.append(node('p',(doc.title||doc.path)+' · '+doc.authorId),node('small','关联对象（作者填写）：'+(doc.relatedTo||'未填写')+' · 标签：'+(doc.tags||[]).join('、')),original(doc));panel.append(section)}
if(!posts.length)panel.append(node('p','尚无居民投稿。指南与模板不是居民经历。'));}
function renderApps(data){const apps=document.getElementById('apps');apps.replaceChildren();document.getElementById('app-content').replaceChildren();
if(!data.cityApps){apps.append(node('p','此实验尚未安装城市应用入口。'));return}
for(const app of data.cityApps.apps){const card=node('article','');card.append(node('h3',app.title),node('p',app.description));for(const channel of app.channels){const button=node('button',channel.title);button.type='button';button.addEventListener('click',()=>showChannel(data,channel));card.append(button)}apps.append(card)}}
form.addEventListener('submit',async e=>{e.preventDefault();status.textContent='读取中…';try{const r=await fetch('/admin/report',{headers:{Authorization:'Bearer '+document.getElementById('token').value}});if(!r.ok)throw new Error('认证失败或服务不可用');const data=await r.json();status.textContent='模拟时刻 '+data.simulationTime+' · 提交 '+data.revision+' · 货币供给 '+data.moneySupply;renderApps(data);
const people=document.getElementById('people');people.replaceChildren();for(const p of data.residents){const card=node('article','');card.append(node('h3',p.displayName),node('small',p.id),node('pre',JSON.stringify({world:p.world,activity:p.activity,cognition:p.cognition},null,2)));people.append(card)}const details=document.getElementById('details');details.replaceChildren();for(const key of ['turns','spaces','documents','messages','trace']){const d=node('details','');d.append(node('summary',key+' · '+data[key].length),node('pre',JSON.stringify(data[key],null,2)));details.append(d)}}catch(err){status.textContent=err.message}});`;
